# Generated by Django 4.2.20 on 2025-03-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('first_episode', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('music_author', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=100)),
                ('telegram_channel', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('poster', models.ImageField(upload_to='series/posters')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='series/backdrops')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('part', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=255)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
        ),
        migrations.CreateModel(
            name='Casts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
        ),
    ]
