# Generated by Django 4.2.20 on 2025-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='part',
            field=models.IntegerField(max_length=6),
        ),
    ]
