# Generated by Django 4.2.20 on 2025-03-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_episode_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='episodes/images'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='part',
            field=models.IntegerField(),
        ),
    ]
